version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN} # Rempli via un fichier .env externe
      - POSTGRES_USER=veronica
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=veronicadb
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=veronica
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=veronicadb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: